# Site
name: '+1s'
description: '从苏北出发，穿过工程、互联网与人工智能，持续学习，持续建造。'
logo: 'assets/images/logo-plus-one-second.svg'
favicon: 'assets/images/logo-plus-one-second.svg'
baseurl: ''
disqus: 'demowebsite'
email: 'heyuwei.efrei@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           波斯王子
      site:           https://www.plus1s.cn
      avatar:         /assets/images/avatar1.jpg
      bio:            "去读书吧，发现不一样的世界！😉"
      email:          heyuwei.efrei@gmail.com
      twitter:        https://www.twitter.com/Heisaman_1

    jane:
      name:           沙俄女孩
      site:           https://www.plus1s.cn
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          varchu1004@126.com
      twitter:        https://twitter.com/heisaman0305
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

url: http://blog.plus1s.cn

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
# encoding: chcp 65001
